"""
pre_migrate.py

Directly applies critical missing columns to the production database using
ADD COLUMN IF NOT EXISTS before Alembic runs.

This acts as a safety net for the recurring problem where the alembic_version
table is stamped at 'head' (via create_all fallback) but certain columns were
never actually added. In that state alembic upgrade head is a no-op, so this
script ensures the columns exist regardless of migration history.

Safe to run on every startup — ADD COLUMN IF NOT EXISTS is idempotent.
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import text
from core import config

# (table, column, sql_type_and_default)
# Only columns that have been observed missing in production.
CRITICAL_COLUMNS = [
    # Added by 20260329_kontokaz_features
    ("loans", "is_recurrent",        "BOOLEAN NOT NULL DEFAULT FALSE"),
    ("loans", "duration_months",      "INTEGER"),
    ("loans", "payment_frequency",    "VARCHAR(20)"),
    ("loans", "interest_rate",        "FLOAT"),
    ("loans", "lender_name",          "VARCHAR"),
    ("jobs",  "auto_clockin_enabled", "BOOLEAN NOT NULL DEFAULT FALSE"),
    ("jobs",  "minimum_break_minutes","INTEGER"),
    # Added by 20260403_ot_rejected
    ("time_logs", "overtime_rejected", "BOOLEAN NOT NULL DEFAULT FALSE"),
    # Added by 20260402_sector_country_year_grade
    ("sectors", "country_code", "VARCHAR(2) NOT NULL DEFAULT 'MU'"),
    ("sectors", "currency",     "VARCHAR(10) NOT NULL DEFAULT 'MUR'"),
    # Added later — sector_grades name column
    ("sector_grades", "grade", "VARCHAR"),
    # user_rights dispute workflow fields
    ("user_rights", "channel",         "VARCHAR(20) NOT NULL DEFAULT 'internal'"),
    ("user_rights", "assigned_to",     "INTEGER"),
    ("user_rights", "internal_notes",  "TEXT"),
    ("user_rights", "resolution",      "TEXT"),
    ("user_rights", "closed_at",       "TIMESTAMPTZ"),
    ("user_rights", "closed_by",       "INTEGER"),
    # users
    ("users", "expo_push_token",              "VARCHAR"),
    ("users", "company_onboarding_status",    "VARCHAR DEFAULT 'pending'"),
    ("users", "verification_note",            "VARCHAR"),
    # private_users
    ("private_users", "department_id", "INTEGER"),
    ("private_users", "role",          "VARCHAR(20) NOT NULL DEFAULT 'employee'"),
    # companies
    ("companies", "vat",                  "VARCHAR(50)"),
    ("companies", "annual_leave_budget",  "INTEGER DEFAULT 0"),
    # leaves
    ("leaves", "approved_by",        "INTEGER"),
    ("leaves", "approved_at",        "TIMESTAMPTZ"),
    ("leaves", "rejection_reason",   "VARCHAR"),
    ("leaves", "approver_comments",  "VARCHAR"),
    # sector_category_salaries
    ("sector_category_salaries", "sector_grade_id", "INTEGER"),
    ("sector_category_salaries", "effective_from",  "DATE"),
    ("sector_category_salaries", "productivity",    "NUMERIC(12,2)"),
    ("sector_category_salaries", "unit",            "VARCHAR"),
    ("sector_category_salaries", "notes",           "VARCHAR"),
]

# Whole TABLES observed missing in production because the alembic stamp is ahead
# of the real schema (create_all/stamp bootstrap), so `alembic upgrade head`
# no-ops and never runs the CREATE. pre_migrate only handled missing COLUMNS;
# a missing table needs the same treatment. Each statement is idempotent
# (CREATE TABLE/INDEX IF NOT EXISTS, CREATE OR REPLACE, DROP ... IF EXISTS), so
# it's safe on every boot and a no-op once the table exists. RLS enablement is
# intentionally NOT replicated here — RLS is not active on prod yet, and forcing
# it on one table out of band could block access; the RLS migration owns that.
CRITICAL_TABLES = [
    # employee_country_assignments — read by PrivateUser.effective_country_code
    # during EVERY showUser serialization (login, employee lists). Missing table
    # 500s the whole response. Mirrors employee_country_assignments_20260720.
    (
        "employee_country_assignments",
        [
            """
            CREATE TABLE IF NOT EXISTS employee_country_assignments (
                id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                private_user_id  INTEGER NOT NULL
                                 REFERENCES private_users(private_user_id) ON DELETE CASCADE,
                country_code     VARCHAR(2) NOT NULL REFERENCES countries(code),
                reason           VARCHAR(32) NOT NULL
                                 CHECK (reason IN ('mission', 'transfer_same_company', 'transfer_new_company')),
                effective_from   DATE NOT NULL,
                effective_to     DATE,
                new_company_id   INTEGER REFERENCES companies(company_id) ON DELETE SET NULL,
                notes            TEXT,
                created_by_user_id INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
                created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
                archived_at      TIMESTAMPTZ,
                company_id       INTEGER
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_employee_country_assignments_private_user_id ON employee_country_assignments (private_user_id)",
            "CREATE INDEX IF NOT EXISTS ix_employee_country_assignments_company_id ON employee_country_assignments (company_id)",
            """
            CREATE UNIQUE INDEX IF NOT EXISTS uq_employee_country_open_assignments
            ON employee_country_assignments (private_user_id)
            WHERE effective_to IS NULL AND archived_at IS NULL
            """,
            """
            CREATE OR REPLACE FUNCTION _set_employee_country_assignments_company_id() RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.company_id IS NULL THEN
                    SELECT company_id INTO NEW.company_id
                    FROM private_users WHERE private_users.private_user_id = NEW.private_user_id;
                END IF;
                RETURN NEW;
            END; $$ LANGUAGE plpgsql
            """,
            "DROP TRIGGER IF EXISTS trg_employee_country_assignments_set_company_id ON employee_country_assignments",
            "CREATE TRIGGER trg_employee_country_assignments_set_company_id BEFORE INSERT ON employee_country_assignments "
            "FOR EACH ROW EXECUTE FUNCTION _set_employee_country_assignments_company_id()",
        ],
    ),
]


def main():
    engine = config.get_engine_from_settings()
    if not engine:
        print("[pre_migrate] No DB engine — skipping")
        return

    with engine.connect() as conn:
        # Without this, an ALTER TABLE stuck behind another session's lock on
        # the same table hangs indefinitely — no exception, no log line, just
        # a silent boot that never reaches uvicorn until DO's health check
        # times out. A short lock_timeout turns that into a fast, caught
        # exception (below) so one contended table can't block every other
        # column, or the whole deploy.
        conn.execute(text("SET lock_timeout = '5s'"))
        for table, column, col_def in CRITICAL_COLUMNS:
            try:
                conn.execute(
                    text(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} {col_def}")
                )
                conn.commit()
                print(f"[pre_migrate] ✓ {table}.{column} ensured")
            except Exception as e:
                print(f"[pre_migrate] Warning — {table}.{column}: {e}")
                try:
                    conn.rollback()
                except Exception:
                    pass

        # Ensure whole tables that may be missing (alembic stamped ahead).
        for table_name, statements in CRITICAL_TABLES:
            try:
                for stmt in statements:
                    conn.execute(text(stmt))
                conn.commit()
                print(f"[pre_migrate] ✓ table {table_name} ensured")
            except Exception as e:
                print(f"[pre_migrate] Warning — table {table_name}: {e}")
                try:
                    conn.rollback()
                except Exception:
                    pass


# NOTE: ensure_model_schema() is intentionally NOT called from main(). main()
# runs BEFORE `alembic upgrade head`; the comprehensive model-diff must run
# AFTER it (see scripts/post_migrate.py), otherwise it would pre-create a column
# a brand-new forward migration then tries to add — failing that (non-idempotent)
# migration and aborting the deploy. It is invoked from post_migrate.py instead.
def ensure_model_schema():
    """Bring the physical schema up to the ORM model definitions, idempotently.

    Root cause this addresses: prod's alembic_version is stamped ahead of the
    real schema (a create_all + stamp bootstrap), so `alembic upgrade head`
    no-ops and any migration that adds a table/column is silently skipped —
    surfacing later as UndefinedTable / UndefinedColumn 500s, one casualty at a
    time (employee_country_assignments, then payroll_runs.fx_snapshot, …).

    Instead of hand-listing each casualty, diff the live schema against the ORM
    metadata and repair drift:
      * create any missing TABLE from its model definition (FK-dependency order), and
      * add any missing COLUMN as NULLABLE — existence is what stops the 500; we
        deliberately do NOT force NOT NULL / defaults, so ADD COLUMN can never
        fail on a populated table.

    Safety: a correct schema is a complete no-op. Every step is
    checkfirst / IF NOT EXISTS / per-object try-except, and the caller treats any
    failure as non-fatal — so this can never fail a boot. RLS/triggers/CHECKs
    that live only in migrations are intentionally not reconstructed here; the
    goal is strictly "no missing table/column 500s", not a migration replacement.
    """
    import core.model  # noqa: F401 — populates Base.metadata with every model
    from core.base_class import Base
    from sqlalchemy import inspect as sa_inspect

    engine = config.get_engine_from_settings()
    if not engine:
        print("[schema_ensure] No DB engine — skipping")
        return

    created_tables = 0
    added_cols = 0
    insp = sa_inspect(engine)
    existing_tables = set(insp.get_table_names())

    with engine.connect() as conn:
        # Hard time caps so a slow/blocked statement can NEVER hang the boot: a
        # DDL stuck behind another session's lock errors out after lock_timeout
        # (caught below) instead of waiting forever, so this can't wedge a deploy.
        # Every statement here is purely additive (CREATE/ADD ... IF NOT EXISTS),
        # so a timeout just means "retry next boot" — never data loss.
        for guc in ("SET lock_timeout = '5s'", "SET statement_timeout = '30s'"):
            try:
                conn.execute(text(guc))
                conn.commit()
            except Exception:
                pass

        # 1) Missing tables — create from the model (sorted_tables = FK order).
        for table in Base.metadata.sorted_tables:
            if table.name in existing_tables:
                continue
            try:
                table.create(bind=conn, checkfirst=True)
                conn.commit()
                created_tables += 1
                print(f"[schema_ensure] ✓ created missing table {table.name}")
            except Exception as e:
                print(f"[schema_ensure] table {table.name}: {e}")
                try:
                    conn.rollback()
                except Exception:
                    pass

        # 2) Missing columns on existing tables — ADD COLUMN IF NOT EXISTS
        # (nullable, no default → a metadata-only change in Postgres, so the
        # ACCESS EXCLUSIVE lock is held for microseconds; no table rewrite, no
        # meaningful contention with the still-serving old instance).
        insp = sa_inspect(engine)
        live_tables = set(insp.get_table_names())
        for table in Base.metadata.sorted_tables:
            if table.name not in live_tables:
                continue
            try:
                existing_cols = {c["name"] for c in insp.get_columns(table.name)}
            except Exception:
                continue
            for col in table.columns:
                if col.name in existing_cols:
                    continue
                try:
                    coltype = col.type.compile(dialect=engine.dialect)
                except Exception as e:
                    print(f"[schema_ensure] skip {table.name}.{col.name} (type compile failed: {e})")
                    continue
                try:
                    conn.execute(text(
                        f'ALTER TABLE "{table.name}" ADD COLUMN IF NOT EXISTS "{col.name}" {coltype}'
                    ))
                    conn.commit()
                    added_cols += 1
                    print(f"[schema_ensure] ✓ added {table.name}.{col.name} ({coltype})")
                except Exception as e:
                    print(f"[schema_ensure] {table.name}.{col.name}: {e}")
                    try:
                        conn.rollback()
                    except Exception:
                        pass

    if created_tables == 0 and added_cols == 0:
        print("[schema_ensure] schema matches models — nothing to repair")
    else:
        print(f"[schema_ensure] repaired drift: {created_tables} table(s), {added_cols} column(s)")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"[pre_migrate] Non-fatal error: {e}")
        sys.exit(0)
