"""Employee country assignments — effective-dated missions & transfers

Creates `employee_country_assignments`, the effective-dated record of a user's
country changing over time (foreign mission / transfer). Mirrors the proven
`employee_salary_assignments` pattern (effective windows, supersede-on-create,
audit trail) and follows the standard indirect-table RLS conventions
(denormalized `company_id` derived from `private_users.company_id`, BEFORE
INSERT trigger, `tenant_isolation_*` policy, FORCE RLS).

Phase 1 scope: display/currency only. The payroll engine is NOT
assignment-aware yet (Phase 2, gated) — nothing here changes payroll behavior.

Revision ID: employee_country_assignments_20260720
Revises: salary_ccy_backfill_20260720
Create Date: 2026-07-20
"""
from alembic import op


revision = "country_assignments_20260720"
down_revision = "salary_ccy_backfill_20260720"
branch_labels = None
depends_on = None

_TABLE = "employee_country_assignments"


def upgrade() -> None:
    op.execute(f"""
        CREATE TABLE IF NOT EXISTS {_TABLE} (
            id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            private_user_id  INTEGER NOT NULL
                             REFERENCES private_users(private_user_id) ON DELETE CASCADE,
            country_code     VARCHAR(2) NOT NULL REFERENCES countries(code),
            reason           VARCHAR(32) NOT NULL
                             CHECK (reason IN ('mission', 'transfer_same_company', 'transfer_new_company')),
            effective_from   DATE NOT NULL,
            effective_to     DATE,
            new_company_id   INTEGER REFERENCES companies(company_id) ON DELETE SET NULL,
            notes            TEXT,
            created_by_user_id INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
            created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            archived_at      TIMESTAMPTZ,
            company_id       INTEGER
            -- company_id is denormalized by RLS migration conventions below
        )
    """)
    op.execute(f"CREATE INDEX IF NOT EXISTS ix_{_TABLE}_private_user_id ON {_TABLE} (private_user_id)")
    op.execute(f"CREATE INDEX IF NOT EXISTS ix_{_TABLE}_company_id ON {_TABLE} (company_id)")
    op.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS uq_employee_country_open_assignments
        ON employee_country_assignments (private_user_id)
        WHERE effective_to IS NULL AND archived_at IS NULL
    """)

    # Denormalize company_id from private_users (standard indirect-table RLS).
    op.execute("""
        UPDATE employee_country_assignments c
        SET company_id = p.company_id
        FROM private_users p
        WHERE c.private_user_id = p.private_user_id AND c.company_id IS NULL
    """)
    op.execute(f"""
        CREATE OR REPLACE FUNCTION _set_{_TABLE}_company_id() RETURNS TRIGGER AS $$
        BEGIN
            IF NEW.company_id IS NULL THEN
                SELECT company_id INTO NEW.company_id
                FROM private_users WHERE private_users.private_user_id = NEW.private_user_id;
            END IF;
            RETURN NEW;
        END; $$ LANGUAGE plpgsql
    """)
    op.execute(f"DROP TRIGGER IF EXISTS trg_{_TABLE}_set_company_id ON {_TABLE}")
    op.execute(f"CREATE TRIGGER trg_{_TABLE}_set_company_id BEFORE INSERT ON {_TABLE} "
               f"FOR EACH ROW EXECUTE FUNCTION _set_{_TABLE}_company_id()")

    # RLS — same policy shape as every other company-scoped table.
    body = (
        "NULLIF(current_setting('app.company_id', true), '') IS NULL"
        f" OR current_setting('app.company_id', true) = '*'"
        f" OR {_TABLE}.company_id::text = current_setting('app.company_id', true)"
        " OR employee_country_assignments.company_id IS NULL"
    )
    op.execute(f"ALTER TABLE {_TABLE} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {_TABLE} FORCE ROW LEVEL SECURITY")
    op.execute(f"DROP POLICY IF EXISTS tenant_isolation_{_TABLE} ON {_TABLE}")
    op.execute(f"CREATE POLICY tenant_isolation_{_TABLE} ON {_TABLE} "
               f"USING ({body}) WITH CHECK ({body})")


def downgrade() -> None:
    op.execute(f"DROP POLICY IF EXISTS tenant_isolation_{_TABLE} ON {_TABLE}")
    op.execute(f"ALTER TABLE {_TABLE} DISABLE ROW LEVEL SECURITY")
    op.execute(f"DROP TRIGGER IF EXISTS trg_{_TABLE}_set_company_id ON {_TABLE}")
    op.execute(f"DROP FUNCTION IF EXISTS _set_{_TABLE}_company_id()")
    op.execute(f"DROP TABLE IF EXISTS {_TABLE}")
